import numpy as np
import torch
import torch.nn as nn
from transformers import GPT2Config, GPT2Model


class GPT2_QAOA(nn.Module):
    """
    Implements Generative QAOA (GQAOA) for portfolio optimization using transformers.GPT2Model to
    optimize QAOA circuit parameters.

    Attributes:
        vocab_size: (int) Discretization size for the parameters gamma, beta of the QAOA circuit
        max_depth: (int) Maximum depth of QAOA that will be generated
        n_embd (int): Dimensionality of the embeddings and hidden states.
        n_layer (int): Number of hidden layers in the Transformer encoder.
        n_head (int): Number of attention heads for each attention layer in the Transformer encoder.
    """

    def __init__(self,
                vocab_size,
                max_depth,
                n_embd=192,
                n_layer=4,
                n_head=8):
        """
        Initializes the GQAOA instance.

        Args:
            vocab_size: (int) Discretization size for the parameters gamma, beta of the QAOA circuit
            max_depth: (int) Maximum depth of QAOA that will be generated
            n_embd (int): Dimensionality of the embeddings and hidden states.
            n_layer (int): Number of hidden layers in the Transformer encoder.
            n_head (int): Number of attention heads for each attention layer in the Transformer encoder.
        """

        super(GPT2_QAOA, self).__init__()
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        config = GPT2Config(
            vocab_size=vocab_size + 1,
            n_positions=max_depth * 2,
            n_ctx=max_depth * 2,
            n_embd=n_embd,
            n_layer=n_layer,
            n_head=n_head,
        )
        self.transformer = GPT2Model(config)
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self._initialize_weights()

        # Define mappings from tokens to angles for QAOA.
        self.vocab_gamma = np.linspace(0, 2*np.pi, vocab_size)
        self.vocab_beta = np.linspace(0, 2*np.pi, vocab_size)

        self.to(self.device)

    def _initialize_weights(self):
        """
        Weight initialization for the transformer and lm_head.
        """

        for module in self.transformer.modules():
            if isinstance(module, nn.Linear):
                nn.init.normal_(module.weight, mean=0, std=0.02)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)
            elif isinstance(module, nn.Embedding):
                nn.init.normal_(module.weight, mean=0, std=0.02)
        nn.init.normal_(self.lm_head.weight, mean=0, std=0.02)
        nn.init.zeros_(self.lm_head.bias)

    def forward(self, input_ids, beta_temp, full_input_ids=None):
        """
        Predict the next id of the QAOA parameter.

        Args:
            input_ids: (torch.Tensor [1, 1]) The ids already generated
            beta_temp: (float) The inverse of temperature, controll the randomness of the stochastic process
            full_input_ids: (List(torch.Tensor [1])) Optional. The already set indexes that will be generated by the model. In that case,
            the model only produces different logits values, depending in the current state.

        Returns:
            (float, int): Logit values for each predicted id and the id generated by stochastic process
        """

        outputs = self.transformer(input_ids)
        hidden_states = outputs.last_hidden_state
        hidden_states = hidden_states[:, -1, :]
        logits = self.lm_head(hidden_states)
        logits = logits.view(1, -1)

        pred_probabilities = torch.softmax(-beta_temp*logits, dim=1)[0]
        pred_probabilities = pred_probabilities.nan_to_num(0.0).clamp(min=0)
        if pred_probabilities.sum() == 0:
            pred_probabilities = torch.ones_like(pred_probabilities)
        pred_probabilities = pred_probabilities / pred_probabilities.sum()
        sample_index = torch.multinomial(pred_probabilities, num_samples=1)
        if full_input_ids is not None:
            sample_index = full_input_ids[input_ids.shape[1]-1]

        response = logits[0][sample_index], (sample_index+1).view(1, 1), logits[0]
        return response

    def generate_parameter_sequence(self, beta_temp, depth, full_input_ids=None, start_token=0):
        """
        Autoregressively generate the sequence of ids of length 2 * depth, for the QAOA circuit parameters.

        Args:
            beta_temp: (float) The inverse of temperature, controll the randomness of the stochastic process
            depth: (int) QAOA depth
            full_input_ids: (List(torch.Tensor [1])) Optional. The already set indexes that will be generated by the model. In that case,
            the model only produces different logits values, depending in the current state.
            start_token: (int) The first token that will start the process

        Returns:
            (List(tuple)): Logits and ids generated for each QAOA layer

        """
        input_ids = torch.tensor([[start_token]], dtype=torch.long, device=self.device)
        model_forward = self.forward(input_ids, beta_temp, full_input_ids)
        data = [model_forward[:2]]
        logits = [model_forward[2]]
        w_less_full_input_ids = (logits[-1][logits[-1]<model_forward[0]]).sum()
        for i in range(2*depth-1):
            input_ids = torch.cat((input_ids, data[-1][1]), dim=1)
            model_forward = self.forward(input_ids, beta_temp, full_input_ids)
            data.append(model_forward[:2])
            logits.append(model_forward[2])
            w_less_full_input_ids += (logits[-1][logits[-1]<model_forward[0]]).sum()

        return data, w_less_full_input_ids, logits

    def forward_qc(self, beta_temp, depth, full_input_ids=None):
        """
        Call self.forward to predict the QAOA circuit parameters and then call the QPU to run the circuit and
        get the measured energy.

        Args:
            beta_temp: (float) The inverse of temperature, controll the randomness of the stochastic process
            depth: (int) QAOA depth
            full_input_ids: (List(torch.Tensor [1])) Optional. The already set indexes that will be generated by the model. In that case,
            the model only produces different logits values, depending in the current state.

        Returns:
            (float, List, List, List): Sum of the logits referring to the circuit parameter IDs;
            Measured energy; Ids of the QAOA parameters; Gamma QAOA parameters; Beta QAOA parameters.

        """

        data, w_less_full_input_ids, logits = self.generate_parameter_sequence(beta_temp, depth, full_input_ids)
        sum_w = 0
        gamma_array = []
        beta_array = []

        full_input_ids_response = []
        for i in range(2*depth):
            full_input_ids_response.append(data[i][1][0]-1)

        for i in range(depth):
            gamma = self.vocab_gamma[full_input_ids_response[2*i]]
            beta = self.vocab_beta[full_input_ids_response[2*i+1]]
            sum_w += data[2*i][0]
            sum_w += data[2*i+1][0]
            gamma_array.append(gamma)
            beta_array.append(beta)

        return sum_w, w_less_full_input_ids, logits, full_input_ids_response, gamma_array, beta_array
